# Generated by Django 5.0 on 2024-01-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
